services:

  api:
    build: .
    container_name: ai-business-os-api
    restart: unless-stopped

    ports:
      - "8000:8000"

    env_file:
      - .env

    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: ai-business-os-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: ai_user
      POSTGRES_PASSWORD: ai_password
      POSTGRES_DB: ai_business_os

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: