"""update company and add user table

Revision ID: 9ff16406243e
Revises: 802833e7d43d
Create Date: 2026-08-03 19:02:15.403913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff16406243e'
down_revision: Union[str, Sequence[str], None] = '802833e7d43d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('slug', sa.String(length=255), nullable=False))
    op.add_column('companies', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('companies', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('companies', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_companies_slug'), 'companies', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_slug'), table_name='companies')
    op.drop_column('companies', 'is_active')
    op.drop_column('companies', 'updated_at')
    op.drop_column('companies', 'created_at')
    op.drop_column('companies', 'slug')
    # ### end Alembic commands ###
